### ISSUE TITLE
How to display more than 1 image horizontally?

### ISSUE THREAD

**Issue by groovybits** [VolkovLabs/business-media#133]
Hi I would like to display a set of received images not just 1 as a horizontal strip of images. Is this possible now? If not how could I add this feature? I can add it if I know what to do / get help with state and current implementation details. Thanks!

**Comment by mikhail-vl** [comment]
@groovybits You can use repeat panel by variables to display more than one panel.

  Panel support navigation and auto-play to display multiple images one by one if it works for you.
