### ISSUE TITLE
Image with more height than panel size

### ISSUE THREAD

**Issue by MrFiestaxxl** [VolkovLabs/business-media#139]
We want to use the panel for displaying Screenshots of websites from an api. Which works flawlessly. But Website Screenshots tend to be longer than our panel. 

We use now a css addon with "overflow-y" enabled as "scroll" it would be nice to have an option Original with scroll. Like when you load an html image in the standard text panel.

**Comment by mikhail-vl** [comment]
@MrFiestaxxl Thank you for opening the feature request.

  We will add in the upcoming release.
