### ISSUE TITLE
Business Media Plugin Images Not Displaying on Snapshot.raintank.io

### ISSUE THREAD

**Issue by K-721** [VolkovLabs/business-media#148]
I'm having an issue with the Business Media plugin. It works perfectly on my localhost, but when I share my dashboard via snapshot.raintank.io, I encounter an image error stating, "Image renderer plugin not installed."

Is there a way to share my dashboard, including the Business Media plugin content, with users who don’t have Grafana installed, and without requiring them to install anything?

Thanks in advance!

**Comment by mikhail-vl** [comment]
@K-721 `snapshot.raintank.io` is managed by Grafana team and they control installed plugins. You can open support request to install it, but we have no insight how Grafana operates it.

  Regarding sharing dashboard, Grafana introduced Public Dashboards, which has some limitations, but overall designed exactly for what you are looking for: https://grafana.com/docs/grafana/latest/dashboards/dashboard-public/

**Comment by K-721** [comment]
Hello Sir @mikhail-vl, thank you for the information! I was able to resolve the issue by exporting my dashboard as a JSON file and hosting it in Grafana Cloud instead. This approach allowed me to share the dashboard internally without making it public. The "image renderer plugin" issue was no longer a problem, and the Business Media plugin worked perfectly. Appreciate your reply and am grateful for the VolkovLabs plugins! Thanks!

**Comment by mikhail-vl** [comment]
@K-721 Great to hear! Let us know if there is anything else.
