### ISSUE TITLE
Panel stuck on No Results Message and wont refresh

### ISSUE THREAD

**Issue by AlmiS** [VolkovLabs/business-media#149]
I am experiencing issues when using the panel to display images. The data for the panel is loaded in base64 format from a JSON api using the Infinity plugin. The query is setup such that a dashboard variable controls which data is loaded from the API. Everything works as expected and images are shown correctly, except in the following case:

If the query does not return any results, eg. the query does not fail it just returns no rows, then the panel shows the "No Results Message" as expected. However, when I then change the dashboard variable, the query updates and returns rows, but the panel fails to refresh. Using a table view instead, I can see that the query and data does refresh, but the media panel seems stuck at the "No Results Message".

Any help fixing this issue would be greatly appreciated! Thanks

Grafana version: 11.3.1
Business Media Plugin: 6.1.0

**Comment by mikhail-vl** [comment]
@AlmiS Thank you for reporting the issue.

  Grafana 11.3 has breaking changes in the way how panel refresh reacts to the refresh event and we may need to update panel accordingly. We will look into it.

**Comment by vitPinchuk** [comment]
@AlmiS Thank you for your question

Please, could you provide some more details on how data looks in a table view mode for cases when there is nothing and after a new request (screenshots, etc.)? You can also record a video if possible.

I've tried to reproduce the issue behavior. It seems to work as expected.

Thanks
